<a href="https://colab.research.google.com/github/Juhi-Purswani/Fake_News_detection/blob/master/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
import os
os.chdir('./drive/My Drive/Fake_news_detection')

FileNotFoundError: ignored

In [0]:
import pandas as pd
import numpy as np

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical

from keras.layers import Embedding
from keras.layers import Dense, Input, Flatten, Bidirectional, TimeDistributed
from keras.layers import Conv1D, MaxPooling1D, Embedding,  Dropout
from keras.models import Model

from keras.models import Sequential
from keras.layers.convolutional import Conv3D
from keras.layers.convolutional_recurrent import ConvLSTM2D
from keras.layers.normalization import BatchNormalization
import numpy as np
from matplotlib import pyplot as plt
from keras.layers import Dense, Embedding, LSTM, GRU

import string
from nltk.corpus import stopwords
import nltk
import re

In [0]:
data_train=pd.read_csv('data/train2.tsv',delimiter='\t',encoding='utf-8',names=["id", "label", "title", "Coverage","i", "lal", "Ed", "Cerage","d", "lbel", "Egtd", "Covage","Dvds","cds","text"])

In [31]:
data_train.drop(['id','Coverage','i','lal','Ed','Cerage','d','lbel','Egtd','Covage','Dvds','cds'],axis=1,inplace=True)
data_train

label  ...                                               text
0            false  ...  That's a premise that he fails to back up. Ann...
1        half-true  ...  Surovell said the decline of coal "started whe...
2      mostly-true  ...  Obama said he would have voted against the ame...
3            false  ...  The release may have a point that Mikulskis co...
4        half-true  ...  Crist said that the economic "turnaround start...
5             true  ...  But Vos specifically used the word "fired," wh...
6      barely-true  ...  But determining that would take significant de...
7        half-true  ...  However, it was not that bill, but another one...
8        half-true  ...  But Johnson is correct that many other factors...
9      mostly-true  ...  Considering that the $532 million figure cover...
10     mostly-true  ...  The senators correct that Latino voters put Ob...
11       half-true  ...  So where does this leave us?On Sanders side, h...
12           false  ...                                                NaN
13     mostly-true  ...  Doonesbury, aka Garry Trudeau, said the govern...
14     barely-true  ...  With all the talk about problems with the heal...
15       half-true  ...  Sanders said that "in this last election in No...
16            true  ...  I firmly object to all 'buy America' restricti...
17     barely-true  ...  And the debt is a result of tax cuts as well a...
18       half-true  ...  Moore said that when the International Finance...
19     mostly-true  ...  Our ruling  Lew said that "almost 100,000 peop...
20           false  ...  It didnt, in other words, change the final res...
21     mostly-true  ...  Bolling said the United States has "the highes...
22     mostly-true  ...  Clinton said, "We just had the best year for t...
23       half-true  ...  Walker changed course to a muddier position, w...
24     barely-true  ...  The Planned Parenthood Action Fund aid said th...
25           false  ...  Pelosi said, "I don't know who (Jonathan Grube...
26     mostly-true  ...  Clinton said that "hate crimes against America...
27       half-true  ...  And, Jillson said, he would not term Perrys 06...
28           false  ...  Geller updated the original post, but it did l...
29     mostly-true  ...  Defining which cities, suburbs and townships a...
...            ...  ...                                                ...
10210         true  ...  Whether you agree with his views or not, it's ...
10211         true  ...  "When you do the math and think about how long...
10212    half-true  ...  Nor did we find newspaper stories or press rel...
10213  barely-true  ...  Looking specifically at retail inspections, th...
10214        false  ...  A Facebook meme indicates Ted Cruz has conveni...
10215  barely-true  ...  Leeder said Texas spends "more per day to hous...
10216        false  ...  Bloomberg said that in 1999, "Wayne LaPierre t...
10217    half-true  ...  Public school students consistently outperform...
10218        false  ...  Chambliss said that with Obamacare, "we're fix...
10219    half-true  ...  They added that typically, Kemp does specify i...
10220  mostly-true  ...  A constitutional amendment would preempt any j...
10221        false  ...  It will be interesting to see what happens in ...
10222         true  ...  Redfern's statement that Kasich "has a duty to...
10223  mostly-true  ...  Look for percentage growth figures that level ...
10224  barely-true  ...  That ruling provides some support to her state...
10225    half-true  ...  A few experts argue that it does little to not...
10226  mostly-true  ...  McAuliffe said a judge took the Star Scientifi...
10227   pants-fire  ...  And we could find no record of it. Our rating ...
10228  barely-true  ...  Ross said, "Every day, a black name resume is ...
10229  mostly-true  ...  Lowry said that a leading liberal had written ...
10230  barely-true  ...  Scott said, "Over the past two years, Florida ...
10231    half-true  ...  McAuliffe sai

In [0]:
data_train.title = data_train.title.str.lower()
data_train.text = data_train.text.str.lower()
data_train.title = data_train.title.str.replace(r'\s\s+',' ')
data_train.text = data_train.text.str.replace(r'\s\s+',' ')
data_train.title = data_train.title.str.replace(r'[^\.\w\s]','') #remove everything but characters and punctuation
data_train.text = data_train.text.str.replace(r'[^\.\w\s]','')
data_train.title = data_train.title.str.replace(r'\.\.+','.') #replace multple periods with a single one
data_train.text = data_train.text.str.replace(r'\.\.+','.')
data_train.title = data_train.title.str.strip() 
data_train.text = data_train.text.str.strip()
#data_train.title = re.sub(r '\d+' , '' , data_train.title)
#data_train.text = re.sub(r '\d+' , '' , data_train.text)
#data_train.title = ''.join([i for i in data_train.title if not i.isdigit()])

data_train.title = data_train.title.str.replace('\d+', '')
data_train.text = data_train.text.str.replace('\d+', '')




In [33]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [35]:
stop_words = set(stopwords.words('english'))
data_train.title.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
data_train.text.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

AttributeError: ignored

In [36]:
data_train

label  ...                                               text
0            false  ...  thats a premise that he fails to back up. anni...
1        half-true  ...  surovell said the decline of coal started when...
2      mostly-true  ...  obama said he would have voted against the ame...
3            false  ...  the release may have a point that mikulskis co...
4        half-true  ...  crist said that the economic turnaround starte...
5             true  ...  but vos specifically used the word fired which...
6      barely-true  ...  but determining that would take significant de...
7        half-true  ...  however it was not that bill but another one s...
8        half-true  ...  but johnson is correct that many other factors...
9      mostly-true  ...  considering that the  million figure covers ju...
10     mostly-true  ...  the senators correct that latino voters put ob...
11       half-true  ...  so where does this leave uson sanders side he ...
12           false  ...                                                NaN
13     mostly-true  ...  doonesbury aka garry trudeau said the governme...
14     barely-true  ...  with all the talk about problems with the heal...
15       half-true  ...  sanders said that in this last election in nov...
16            true  ...  i firmly object to all buy america restriction...
17     barely-true  ...  and the debt is a result of tax cuts as well a...
18       half-true  ...  moore said that when the international finance...
19     mostly-true  ...  our ruling lew said that almost  people left p...
20           false  ...  it didnt in other words change the final resul...
21     mostly-true  ...  bolling said the united states has the highest...
22     mostly-true  ...  clinton said we just had the best year for the...
23       half-true  ...  walker changed course to a muddier position wh...
24     barely-true  ...  the planned parenthood action fund aid said th...
25           false  ...    pelosi said i dont know who jonathan gruber is.
26     mostly-true  ...  clinton said that hate crimes against american...
27       half-true  ...  and jillson said he would not term perrys  win...
28           false  ...  geller updated the original post but it did li...
29     mostly-true  ...  defining which cities suburbs and townships ar...
...            ...  ...                                                ...
10210         true  ...  whether you agree with his views or not its cl...
10211         true  ...  when you do the math and think about how long ...
10212    half-true  ...  nor did we find newspaper stories or press rel...
10213  barely-true  ...  looking specifically at retail inspections the...
10214        false  ...  a facebook meme indicates ted cruz has conveni...
10215  barely-true  ...  leeder said texas spends more per day to house...
10216        false  ...  bloomberg said that in  wayne lapierre testifi...
10217    half-true  ...  public school students consistently outperform...
10218        false  ...  chambliss said that with obamacare were fixing...
10219    half-true  ...  they added that typically kemp does specify in...
10220  mostly-true  ...  a constitutional amendment would preempt any j...
10221        false  ...  it will be interesting to see what happens in ...
10222         true  ...  redferns statement that kasich has a duty to r...
10223  mostly-true  ...  look for percentage growth figures that level ...
10224  barely-true  ...  that ruling provides some support to her state...
10225    half-true  ...  a few experts argue that it does little to not...
10226  mostly-true  ...  mcauliffe said a judge took the star scientifi...
10227   pants-fire  ...  and we could find no record of it. our rating ...
10228  barely-true  ...  ross said every day a black name resume is  pe...
10229  mostly-true  ...  lowry said that a leading liberal had written ...
10230  barely-true  ...  scott said over the past two years florida has...
10231    half-true  ...  mcauliffe sai

In [37]:
data_train.isnull().sum()

label     0
title     0
text     84
dtype: int64

In [38]:
data_train.dropna()

label  ...                                               text
0            false  ...  thats a premise that he fails to back up. anni...
1        half-true  ...  surovell said the decline of coal started when...
2      mostly-true  ...  obama said he would have voted against the ame...
3            false  ...  the release may have a point that mikulskis co...
4        half-true  ...  crist said that the economic turnaround starte...
5             true  ...  but vos specifically used the word fired which...
6      barely-true  ...  but determining that would take significant de...
7        half-true  ...  however it was not that bill but another one s...
8        half-true  ...  but johnson is correct that many other factors...
9      mostly-true  ...  considering that the  million figure covers ju...
10     mostly-true  ...  the senators correct that latino voters put ob...
11       half-true  ...  so where does this leave uson sanders side he ...
13     mostly-true  ...  doonesbury aka garry trudeau said the governme...
14     barely-true  ...  with all the talk about problems with the heal...
15       half-true  ...  sanders said that in this last election in nov...
16            true  ...  i firmly object to all buy america restriction...
17     barely-true  ...  and the debt is a result of tax cuts as well a...
18       half-true  ...  moore said that when the international finance...
19     mostly-true  ...  our ruling lew said that almost  people left p...
20           false  ...  it didnt in other words change the final resul...
21     mostly-true  ...  bolling said the united states has the highest...
22     mostly-true  ...  clinton said we just had the best year for the...
23       half-true  ...  walker changed course to a muddier position wh...
24     barely-true  ...  the planned parenthood action fund aid said th...
25           false  ...    pelosi said i dont know who jonathan gruber is.
26     mostly-true  ...  clinton said that hate crimes against american...
27       half-true  ...  and jillson said he would not term perrys  win...
28           false  ...  geller updated the original post but it did li...
29     mostly-true  ...  defining which cities suburbs and townships ar...
30            true  ...  the new york times and abc news said ryan resp...
...            ...  ...                                                ...
10210         true  ...  whether you agree with his views or not its cl...
10211         true  ...  when you do the math and think about how long ...
10212    half-true  ...  nor did we find newspaper stories or press rel...
10213  barely-true  ...  looking specifically at retail inspections the...
10214        false  ...  a facebook meme indicates ted cruz has conveni...
10215  barely-true  ...  leeder said texas spends more per day to house...
10216        false  ...  bloomberg said that in  wayne lapierre testifi...
10217    half-true  ...  public school students consistently outperform...
10218        false  ...  chambliss said that with obamacare were fixing...
10219    half-true  ...  they added that typically kemp does specify in...
10220  mostly-true  ...  a constitutional amendment would preempt any j...
10221        false  ...  it will be interesting to see what happens in ...
10222         true  ...  redferns statement that kasich has a duty to r...
10223  mostly-true  ...  look for percentage growth figures that level ...
10224  barely-true  ...  that ruling provides some support to her state...
10225    half-true  ...  a few experts argue that it does little to not...
10226  mostly-true  ...  mcauliffe said a judge took the star scientifi...
10227   pants-fire  ...  and we could find no record of it. our rating ...
10228  barely-true  ...  ross said every day a black name resume is  pe...
10229  mostly-true  ...  lowry said that a leading liberal had written ...
10230  barely-true  ...  scott said over the past two years florida has...
10231    half-true  ...  mcauliffe sai

In [0]:
texts = []
labels = []

for i in range(data_train.text.shape[0]):
    text1 = data_train.title[i]
    text2 = data_train.text[i]
    text = str(text1) +""+ str(text2)
    texts.append(text)
    labels.append(data_train.label[i])
    
for i in range(len(labels)):
    if(labels[i]=='mostly-true'):
        labels[i] = 'true'
    
    elif(labels[i]=='barely-true'):
        labels[i] = 'false'
    
    elif(labels[i]=='pants-fire'):
        labels[i] = 'false'
    elif(labels[i]=='half-true'):
        labels[i] = 'true'

In [40]:
MAX_SEQUENCE_LENGTH = 1000
MAX_NB_WORDS = 200000
EMBEDDING_DIM = 100

tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
features_train = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

df = pd.DataFrame(labels) 
labels_train = pd.get_dummies(df)

print('Shape of data tensor:', features_train)
print('Shape of label tensor:', labels_train)

indices = np.arange(features_train.shape[0])
np.random.shuffle(indices)
features_train = features_train[indices]
labels_train = labels_train[indices]

Shape of data tensor: [[    0     0     0 ...     9    24  1642]
 [    0     0     0 ...  1355   431  5307]
 [    0     0     0 ...     6     8   172]
 ...
 [    0     0     0 ...   571   526  1822]
 [    0     0     0 ...    14  1137  1906]
 [    0     0     0 ... 16283     8   112]]
Shape of label tensor:        0_false  0_true
0            1       0
1            0       1
2            0       1
3            1       0
4            0       1
5            0       1
6            1       0
7            0       1
8            0       1
9            0       1
10           0       1
11           0       1
12           1       0
13           0       1
14           1       0
15           0       1
16           0       1
17           1       0
18           0       1
19           0       1
20           1       0
21           0       1
22           0       1
23           0       1
24           1       0
25           1       0
26           0       1
27           0       1
28           1       0
2

KeyError: ignored

In [41]:
#Using Pre-trained word embeddings
GLOVE_DIR = "data" 
embeddings_index = {}
f = open(os.path.join(GLOVE_DIR, 'glove.6B.100d.txt'), encoding="utf8")
for line in f:
    values = line.split()
    #print(values[1:])
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Total %s word vectors in Glove.' % len(embeddings_index))

embedding_matrix = np.random.random((len(word_index) + 1, EMBEDDING_DIM))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector
        
embedding_layer = Embedding(len(word_index) + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH)

Total 400000 word vectors in Glove.


In [42]:
embedding_vecor_length = 32
modell = Sequential()
modell.add(embedding_layer)
modell.add(Dropout(0.2))
modell.add(Conv1D(filters=32, kernel_size=5, padding='same', activation='relu'))
modell.add(MaxPooling1D(pool_size=2))
modell.add(Conv1D(filters=64, kernel_size=3, padding='same', activation='relu'))
modell.add(MaxPooling1D(pool_size=2))
modell.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
modell.add(BatchNormalization())
modell.add(Dense(256, activation='relu'))
modell.add(Dense(128, activation='relu'))
modell.add(Dense(64, activation='relu'))
modell.add(Dense(2, activation='softmax'))
modell.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(modell.summary())
modell.fit(features_train, labels_train, epochs=10, batch_size=64)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 1000, 100)         2709100   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000, 100)         0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 1000, 32)          16032     
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 500, 32)           0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 500, 64)           6208      
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 250, 64)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               66000     
__________